### ISSUE TITLE
[BZ-3512] cidlc doesn't build with boost 1.37 and visual studio 2005 update 1

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#3512]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [3512](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=3512) |
| **Reporter** | @jwillemsen |
| **Assigned to** | Jeff Parsons |
| **Product** | CIAO |
| **Component** | CIDL compiler |
| **Version** | 0.6.6 |
| **Platform / OS** | All / Windows NT |
| **Priority** | P3 |
| **Severity** | normal |
| **Status** | RESOLVED |
| **Resolution** | FIXED |
| **Created** | 2008-11-17 09:52:00 -0600 |

---

_Originally posted by @jwillemsen on 2008-11-17 09:52:00 -0600_

---

when trying to build cidlc on svn head with boost 1.37 and vs2005 update 1 installed I do get:

1>------ Build started: Project: IDL3, Configuration: Debug Win32 ------
2>------ Build started: Project: IDL2, Configuration: Debug Win32 ------
1>Compiling...
1>Component.cpp
2>Compiling...
2>Attribute.cpp
1>Parser.cpp
2>Token.cpp
2>Parser.cpp
2>.\Parser.cpp(249) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(249) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(249) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(252) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(252) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(252) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(255) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(255) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(255) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(258) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(258) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(258) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(261) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(261) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(261) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(265) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(265) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(265) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(269) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(269) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(269) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(272) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(272) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(272) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(275) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(275) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(275) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(277) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(277) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(277) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(957) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(957) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(957) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(958) : error C2660: 'CCF::IDL2::Parser::handler::handler' : function does not take 2 arguments
2>.\Parser.cpp(961) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(961) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(961) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(963) : error C2064: term does not evaluate to a function taking 4 arguments
2>        class does not define an 'operator()' or a user defined conversion operator to a pointer-to-function or reference-to-function that takes appropriate number of arguments
2>.\Parser.cpp(969) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(969) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(969) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(970) : error C2660: 'CCF::IDL2::Parser::handler::handler' : function does not take 2 arguments
2>.\Parser.cpp(974) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(974) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(974) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(976) : error C2064: term does not evaluate to a function taking 4 arguments
2>        class does not define an 'operator()' or a user defined conversion operator to a pointer-to-function or reference-to-function that takes appropriate number of arguments
2>.\Parser.cpp(992) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(992) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(992) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(993) : error C2660: 'CCF::IDL2::Parser::handler::handler' : function does not take 2 arguments
2>.\Parser.cpp(996) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(996) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(996) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(998) : error C2064: term does not evaluate to a function taking 4 arguments
2>        class does not define an 'operator()' or a user defined conversion operator to a pointer-to-function or reference-to-function that takes appropriate number of arguments
2>.\Parser.cpp(1004) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1004) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1004) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1005) : error C2660: 'CCF::IDL2::Parser::handler::handler' : function does not take 2 arguments
2>.\Parser.cpp(1009) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1009) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1009) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1011) : error C2064: term does not evaluate to a function taking 4 arguments
2>        class does not define an 'operator()' or a user defined conversion operator to a pointer-to-function or reference-to-function that takes appropriate number of arguments
2>.\Parser.cpp(1046) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1046) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1046) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1047) : error C2660: 'CCF::IDL2::Parser::handler::handler' : function does not take 2 arguments
2>.\Parser.cpp(1050) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1050) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1050) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1052) : error C2064: term does not evaluate to a function taking 4 arguments
2>        class does not define an 'operator()' or a user defined conversion operator to a pointer-to-function or reference-to-function that takes appropriate number of arguments
2>.\Parser.cpp(1058) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1058) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1058) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1059) : error C2660: 'CCF::IDL2::Parser::handler::handler' : function does not take 2 arguments
2>.\Parser.cpp(1063) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1063) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1063) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1065) : error C2064: term does not evaluate to a function taking 4 arguments
2>        class does not define an 'operator()' or a user defined conversion operator to a pointer-to-function or reference-to-function that takes appropriate number of arguments
2>.\Parser.cpp(1081) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1081) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1081) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1082) : error C2660: 'CCF::IDL2::Parser::handler::handler' : function does not take 2 arguments
2>.\Parser.cpp(1085) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1085) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1085) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1087) : error C2064: term does not evaluate to a function taking 4 arguments
2>        class does not define an 'operator()' or a user defined conversion operator to a pointer-to-function or reference-to-function that takes appropriate number of arguments
2>.\Parser.cpp(1093) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1093) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1093) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1094) : error C2660: 'CCF::IDL2::Parser::handler::handler' : function does not take 2 arguments
2>.\Parser.cpp(1098) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1098) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1098) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1100) : error C2064: term does not evaluate to a function taking 4 arguments
2>        class does not define an 'operator()' or a user defined conversion operator to a pointer-to-function or reference-to-function that takes appropriate number of arguments
2>.\Parser.cpp(1136) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1136) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1136) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1137) : error C2660: 'CCF::IDL2::Parser::handler::handler' : function does not take 2 arguments
2>.\Parser.cpp(1140) : error C2332: 'struct' : missing tag name
2>.\Parser.cpp(1140) : error C2039: '<unnamed-tag>' : is not a member of 'CCF::IDL2::SemanticAction::Factory'
2>        c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF/IDL2/SemanticAction/Factory.hpp(38) : see declaration of 'CCF::IDL2::SemanticAction::Factory'
2>.\Parser.cpp(1140) : error C2274: 'function-style cast' : illegal as right side of '.' operator
2>.\Parser.cpp(1140) : fatal error C1003: error count exceeds 100; stopping compilation
2>LexicalAnalyzer.cpp
2>Translation.cpp
1>Build log was saved at "file://c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF\IDL3\Static_Debug\IDL3\I386\BuildLog.htm"
1>IDL3 - 0 error(s), 0 warning(s)
1>
1>
1>The build has been canceled at the user's request
1>
2>Build log was saved at "file://c:\ACE\latest\ACE_wrappers\TAO\CIAO\CCF\CCF\IDL2\Static_Debug\IDL2\I386\BuildLog.htm"
2>IDL2 - 102 error(s), 0 warning(s)

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2008-11-17 09:52:18 -0600_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=3512#c1))

---

Added Boris

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2008-11-17 09:52:28 -0600_ ([Bugzilla comment 2](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=3512#c2))

---

Added Will

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2008-11-17 09:56:44 -0600_ ([Bugzilla comment 3](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=3512#c3))

---

ok, easy one to fix, interface is a define in vs2005 also :-(

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2008-11-17 09:58:42 -0600_ ([Bugzilla comment 4](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=3512#c4))

---

Mon Nov 17 15:58:12 UTC 2008  Johnny Willemsen  <jwillemsen@remedy.nl>

        * CCF/CCF/IDL2/Parser.hpp:
          When interface is a define, undef it. Fixes bugzilla 3512

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2008-11-17 09:58:47 -0600_ ([Bugzilla comment 5](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=3512#c5))

---

Mon Nov 17 15:58:12 UTC 2008  Johnny Willemsen  <jwillemsen@remedy.nl>

        * CCF/CCF/IDL2/Parser.hpp:
          When interface is a define, undef it. Fixes bugzilla 3512
