### ISSUE TITLE
[BZ-484] TAO 1.0.15 doesn't seem to compile with GCC 2.95.2

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#484]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [484](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=484) |
| **Reporter** | J. Russell Noseworthy |
| **Assigned to** | DOC Center Support List (internal) |
| **Product** | TAO |
| **Component** | ORB |
| **Version** | 1.0.15 |
| **Platform / OS** | All / All |
| **Priority** | P2 |
| **Severity** | blocker |
| **Status** | RESOLVED |
| **Resolution** | FIXED |
| **Created** | 2000-03-09 14:14:21 -0600 |

---

_Originally posted by J. Russell Noseworthy on 2000-03-09 14:14:21 -0600_

---

gmake: Entering directory
`/home/TAO/1.0.15a/build/SunOS-5.6-Sparc-gcc-2.95.2-opt-mt/TAO/tao'
g++ -W -Wall -Wpointer-arith -pipe  -Wno-return-type -D_POSIX_C_SOURCE=199506L
-D__EXTENSIONS__ -D_POSIX_PTHREAD_SEMANTICS -O2 -DACE_NDEBUG -Wno-uninitialized
-fno-implicit-templates
-I/home/TAO/1.0.15a/build/SunOS-5.6-Sparc-gcc-2.95.2-opt-mt -DACE_HAS_EXCEPTIONS
-DTAO_HAS_AMI=0 -DTAO_HAS_AMI_POLLER=0 -DTAO_HAS_AMI_CALLBACK=0
-DTAO_HAS_RT_CORBA=1 -DTAO_HAS_CORBA_MESSAGING=1
-I/home/TAO/1.0.15a/build/SunOS-5.6-Sparc-gcc-2.95.2-opt-mt/TAO  -c -fPIC -o
.shobj/InterfaceC.o InterfaceC.cpp
InterfaceC.cpp: In method `class CORBA_ExceptionDefSeq *
CORBA_OperationDef::exceptions(CORBA_Environment & =
TAO_default_environment())':
InterfaceC.cpp:9326: no matching function for call to
`TAO_GIOP_Twoway_Invocation::TAO_GIOP_Twoway_Invocation (TAO_Stub *&, const
char[16], TAO_ORB_Core *)'
/home/TAO/1.0.15a/build/SunOS-5.6-Sparc-gcc-2.95.2-opt-mt/TAO/tao/Invocation.i:32:
candidates are: TAO_GIOP_Twoway_Invocation::TAO_GIOP_Twoway_Invocation(TAO_Stub
*, const char *, unsigned int, TAO_ORB_Core *)
/home/TAO/1.0.15a/build/SunOS-5.6-Sparc-gcc-2.95.2-opt-mt/TAO/tao/Invocation.h:241:
TAO_GIOP_Twoway_Invocation::TAO_GIOP_Twoway_Invocation(const
TAO_GIOP_Twoway_Invocation &)
gmake: *** [.shobj/InterfaceC.o] Error 1

**Comment by jwillemsen** [comment]
_Originally posted by Jeff Parsons on 2000-03-09 14:20:59 -0600_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=484#c1))

---

Wed Mar  8 08:59:47 2000  Jeff Parsons  <parsons@cs.wustl.edu>

        * tao/InterfaceC.cpp:
          Added a missing operation name length argument. Thanks to
          Thomas Lockhart <Thomas.G.Lockhart@jpl.nasa.gov> for
          pointing this out.
