### ISSUE TITLE
[BZ-2984] ACE 5.5 does not build on MacOSX 9.0.0 (Leopard)

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#2984]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [2984](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984) |
| **Reporter** | cdi |
| **Assigned to** | cdi |
| **Product** | ACE |
| **Component** | ACE Core |
| **Version** | 5.5 |
| **Platform / OS** | x86 / other |
| **Priority** | P4 |
| **Severity** | normal |
| **Status** | RESOLVED |
| **Resolution** | WORKSFORME |
| **Created** | 2007-07-06 11:06:58 -0500 |

---

_Originally posted by cdi on 2007-07-06 11:06:58 -0500_

---

Following recent POSIX changes Darwin seem to drop support of L_cuserid macro, therefore ACE build fails at configure step (when configuration sanity is checked).

Also, on this version of Darwin there is a compilation error in Handle_Set.inl because ACE_Handle_Set::is_set() method is declared const, but it passes address of a member down to FD_ISSET() which is expanded to an inline function call with a non-constant argument.

Attached patch fixes the build for me (no test suite results yet though).

**Comment by jwillemsen** [comment]
_Originally posted by cdi on 2007-07-06 11:07:37 -0500_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c1))

---

Created attachment [814](https://raw.githubusercontent.com/DOCGroup/bugzilla/main/attachments/BZ-2984/ACE_5_5_Leopard.diff)
Tentative build fixes for Darwin 9.0.0.

| Field | Value |
| --- | --- |
| **Attachment ID** | [814](http://bugzilla.dre.vanderbilt.edu/attachment.cgi?id=814) |
| **Filename** | `ACE_5_5_Leopard.diff` |
| **Description** | Tentative build fixes for Darwin 9.0.0. |
| **Uploaded by** | cdi |
| **Date** | 2007-07-06 11:07:37 -0500 |
| **Size** | 1482 bytes |
| **Patch** | no |
| **Obsolete** | no |
| **Download** | [Download from repository](https://raw.githubusercontent.com/DOCGroup/bugzilla/main/attachments/BZ-2984/ACE_5_5_Leopard.diff) |

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-07-08 04:11:06 -0500_ ([Bugzilla comment 2](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c2))

---

I have merged the change in os_ns_stdio.inl. Can you check the first change on a recent version of ACE? For the FD_ISSET call, does this only expand on macosx9 to a non-const function? We don't see this problem on other platforms, maybe we need to have a ACE_HAS_NONCONST_FD_ISSET? Just adding a cast is not something we want to do in general

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-07-08 18:05:56 -0500_ ([Bugzilla comment 3](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c3))

---

Sun Jul  8 22:05:12 UTC 2007  Johnny Willemsen  <jwillemsen@remedy.nl>

        * ace/OS_NS_stdio.inl (cuserid):
          Only use L_cuserid when it is defined, fixes a problem on MacOS X 9.
          Thanks to Dennis Chernoivanov <cdi at tbricks dot com> for reporting
          this. This is part of bugzilla 2984

**Comment by jwillemsen** [comment]
_Originally posted by cdi on 2007-07-09 01:41:24 -0500_ ([Bugzilla comment 4](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c4))

---

Changing OS_NS_stdio.inl is not enough because cuserid() function declaration in OS_NS_stdio.h makes use of ACE_MAX_USERID macro which expands to L_cuserid, this is what the first hunk of my patch fixes:

@@ -62,6 +62,9 @@
 #   define ACE_MAX_USERID 32
 # else
 #  define ACE_MAX_USERID L_cuserid
+#  if !defined(L_cuserid)
+#    define L_cuserid       9
+#  endif

Speaking of FD_ISSET() macro, to the best of my knowledge Leopard is the only platform where I see such problem. ACE_HAS_NONCONST_FD_ISSET would be fine IMO, but to test it I will need some guidance -- can't get automake scripts to work.

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-07-09 05:49:20 -0500_ ([Bugzilla comment 5](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c5))

---

A quick look yesterday gave me the idea the patch is not possible anymore. For the autoconf, have a look at regular autoconf docu on the web

(In reply to comment #4)
> Changing OS_NS_stdio.inl is not enough because cuserid() function declaration
> in OS_NS_stdio.h makes use of ACE_MAX_USERID macro which expands to L_cuserid,
> this is what the first hunk of my patch fixes:
> 
> @@ -62,6 +62,9 @@
>  #   define ACE_MAX_USERID 32
>  # else
>  #  define ACE_MAX_USERID L_cuserid
> +#  if !defined(L_cuserid)
> +#    define L_cuserid       9
> +#  endif
> 
> Speaking of FD_ISSET() macro, to the best of my knowledge Leopard is the only
> platform where I see such problem. ACE_HAS_NONCONST_FD_ISSET would be fine IMO,
> but to test it I will need some guidance -- can't get automake scripts to work.
>

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-07-09 05:49:43 -0500_ ([Bugzilla comment 6](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c6))

---

to pool

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-07-13 07:21:35 -0500_ ([Bugzilla comment 7](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c7))

---

Please recreate patches based on svn head.

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-07-13 09:34:40 -0500_ ([Bugzilla comment 8](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c8))

---

changed severity

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-07-13 09:38:22 -0500_ ([Bugzilla comment 9](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c9))

---

Can you test this method:

ACE_INLINE int
ACE_Handle_Set::is_set (ACE_HANDLE handle) const
{
  ACE_TRACE ("ACE_Handle_Set::is_set");
#if defined (ACE_HAS_BIG_FD_SET)
  return FD_ISSET (handle,
                   &this->mask_)
    && this->size_ > 0;
#if defined (ACE_HAS_NONCONST_FD_ISSET)
  return FD_ISSET (handle,
                   const_cast<fd_set*> (&this->mask_));
#else
  return FD_ISSET (handle,
                   &this->mask_);
#endif /* ACE_HAS_BIG_FD_SET */
}

Set ACE_HAS_NONCONST_FD_ISSET In your config.h file

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-07-14 02:48:00 -0500_ ([Bugzilla comment 10](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c10))

---

* ace/Handle_Set.inl:
          Added ACE_HAS_NONCONST_FD_ISSET. Is for MacOS Leopard
          Thanks to Dennis Chernoivanov <cdi at tbricks dot com> for reporting
          this. This is part of bugzilla 2984

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-08-06 03:36:06 -0500_ ([Bugzilla comment 11](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c11))

---

back to reporter, can you retest with x.5.10?

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2008-02-12 08:27:01 -0600_ ([Bugzilla comment 12](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2984#c12))

---

closing as workfsforme, macos builds show no real errors
