### ISSUE TITLE
[BZ-4133] mingw posix builds fail due to buggy pthread macros

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#4133]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [4133](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=4133) |
| **Reporter** | Marc Dostie |
| **Assigned to** | DOC Center Support List (internal) |
| **Product** | ACE |
| **Component** | ACE Core |
| **Version** | 6.2.1 |
| **Platform / OS** | x86 / Windows 2008 |
| **Priority** | P3 |
| **Severity** | normal |
| **Status** | NEW |
| **Resolution** |  |
| **Created** | 2013-09-24 09:41:15 -0500 |

---

_Originally posted by Marc Dostie on 2013-09-24 09:41:15 -0500_

---

ACE VERSION: 6.2.1 

    HOST MACHINE and OPERATING SYSTEM: 
Lenovo T410 laptop running Windows 7 
                 
        If on Windows based OS's, which version of WINSOCK do you 
        use?: 
Winsock 2 (ws2_32.dll), version 6.1.7601.17514 

    TARGET MACHINE and OPERATING SYSTEM, if different from HOST: 
Same as host 
                 
    COMPILER NAME AND VERSION (AND PATCHLEVEL): 
MinGW g++ from Qt 5.1.1 distro (c:\Qt\Qt5.1.1\Tools\mingw48_32). 
Output of 'g++ -v': 
---------------------------------------------------------- 
Using built-in specs. 
COLLECT_GCC=C:\Qt\Qt5.1.1\Tools\mingw48_32\bin\g++.exe 
COLLECT_LTO_WRAPPER=c:/qt/qt5.1.1/tools/mingw48_32/bin/../libexec/gcc/i686-w64-mingw32/4.8.0/lto-wrapper.exe 
Target: i686-w64-mingw32 
Configured with: ../../../src/gcc-4.8.0/configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/temp/x32-480-posix-dwarf-r2/mingw32 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-sjlj-exceptions --with-dwarf2 --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=i686 --with-tune=generic --with-host-libstdcxx='-static -lstdc++' --with-libiconv --with-system-zlib --with-gmp=/temp/mingw-prereq/i686-w64-mingw32-static --with-mpfr=/temp/mingw-prereq/i686-w64-mingw32-static --with-mpc=/temp/mingw-prereq/i686-w64-mingw32-static --with-isl=/temp/mingw-prereq/i686-w64-mingw32-static --with-cloog=/temp/mingw-prereq/i686-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='rev2, Built by MinGW-builds project' --with-bugurl=http://sourceforge.net/projects/mingwbuilds/ CFLAGS='-O2 -pipe -I/temp/x32-480-posix-dwarf-r2/libs/include -I/temp/mingw-prereq/x32-zlib/include -I/temp/mingw-prereq/i686-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/temp/x32-480-posix-dwarf-r2/libs/include -I/temp/mingw-prereq/x32-zlib/include -I/temp/mingw-prereq/i686-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/temp/x32-480-posix-dwarf-r2/libs/lib -L/temp/mingw-prereq/x32-zlib/lib -L/temp/mingw-prereq/i686-w64-mingw32-static/lib -L/temp/x32-480-posix-dwarf-r2/mingw32/opt/lib' 
Thread model: posix 
gcc version 4.8.0 (rev2, Built by MinGW-builds project) 
---------------------------------------------------------- 
                 
         
    THE $ACE_ROOT/ace/config.h FILE 
Linked to config-win32.h 

    THE $ACE_ROOT/include/makeinclude/platform_macros.GNU FILE 
include $(ACE_ROOT)/include/makeinclude/platform_mingw32.GNU 
INSTALL_PREFIX=/c/ACE/6.2.1-qt 

    CONTENTS OF $ACE_ROOT/bin/MakeProjectCreator/config/default.features 
    (used by MPC when you generate your own makefiles): 
Didn't use MPC (perhaps I need to?) 

    AREA/CLASS/EXAMPLE AFFECTED: 
ACE build on windows fails with mingw from Qt 5.1.1 release. Perhaps related to the posix threading model compiled into g++. Make output is as follows: 
                 
make[1]: Entering directory `/c/ace/6.2.1-qt/ACE_wrappers/ace' 

GNUmakefile: /c/ace/6.2.1-qt/ACE_wrappers/ace/GNUmakefile.ACE MAKEFLAGS=w 

g++ -O3 -g -mthreads -mtune=pentiumpro -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -DACE_HAS_CUSTOM_EXPORT_MACROS=0 -Wno-unknown-pragmas   -I/c/ace/6.2.1-qt/ACE_wrappers/ -DACE_NO_INLINE -I.. -DACE_BUILD_DLL  -c  -o .shobj/Name_Proxy.o Name_Proxy.cpp 
In file included from c:\qt\qt5.1.1\tools\mingw48_32\lib\gcc\i686-w64-mingw32\4.8.0\include\c++\i686-w64-mingw32\bits\gthr-default.h:35:0, 
                 from c:\qt\qt5.1.1\tools\mingw48_32\lib\gcc\i686-w64-mingw32\4.8.0\include\c++\i686-w64-mingw32\bits\gthr.h:148, 
                 from c:\qt\qt5.1.1\tools\mingw48_32\lib\gcc\i686-w64-mingw32\4.8.0\include\c++\ext\atomicity.h:33, 
                 from c:\qt\qt5.1.1\tools\mingw48_32\lib\gcc\i686-w64-mingw32\4.8.0\include\c++\bits\ios_base.h:39, 
                 from c:\qt\qt5.1.1\tools\mingw48_32\lib\gcc\i686-w64-mingw32\4.8.0\include\c++\ios:42, 
                 from c:\qt\qt5.1.1\tools\mingw48_32\lib\gcc\i686-w64-mingw32\4.8.0\include\c++\ostream:38, 
                 from c:\qt\qt5.1.1\tools\mingw48_32\lib\gcc\i686-w64-mingw32\4.8.0\include\c++\iterator:64, 
                 from c:/ace/6.2.1-qt/ACE_wrappers/ace/String_Base.h:26, 
                 from c:/ace/6.2.1-qt/ACE_wrappers/ace/SString.h:23, 
                 from c:/ace/6.2.1-qt/ACE_wrappers/ace/Service_Gestalt.h:26, 
                 from c:/ace/6.2.1-qt/ACE_wrappers/ace/Service_Config.h:21, 
                 from c:/ace/6.2.1-qt/ACE_wrappers/ace/Name_Proxy.h:32, 
                 from Name_Proxy.cpp:3: 
c:/ace/6.2.1-qt/ACE_wrappers/ace/OS_NS_string.h:444:48: error: expected unqualified-id before 'char' 
   char *strtok_r (char *s, const char *tokens, char **lasts); 
                                                ^ 
c:/ace/6.2.1-qt/ACE_wrappers/ace/OS_NS_string.h:444:48: error: expected ')' before 'char' 
c:/ace/6.2.1-qt/ACE_wrappers/ace/OS_NS_string.h:444:48: error: expected ')' before 'char' 
c:/ace/6.2.1-qt/ACE_wrappers/ace/OS_NS_string.h:444:48: error: expected initializer before 'char' 
c:/ace/6.2.1-qt/ACE_wrappers/ace/Basic_Types.h:317:23: error: expected unqualified-id before 'wchar_t' 
 #  define ACE_WCHAR_T wchar_t 
                       ^ 
c:/ace/6.2.1-qt/ACE_wrappers/ace/OS_NS_string.h:449:65: note: in expansion of macro 'ACE_WCHAR_T' 
   wchar_t *strtok_r (ACE_WCHAR_T *s, const ACE_WCHAR_T *tokens, ACE_WCHAR_T **lasts); 
                                                                 ^ 
c:/ace/6.2.1-qt/ACE_wrappers/ace/Basic_Types.h:317:23: error: expected ')' before 'wchar_t' 
 #  define ACE_WCHAR_T wchar_t 
                       ^ 
c:/ace/6.2.1-qt/ACE_wrappers/ace/OS_NS_string.h:449:65: note: in expansion of macro 'ACE_WCHAR_T' 
   wchar_t *strtok_r (ACE_WCHAR_T *s, const ACE_WCHAR_T *tokens, ACE_WCHAR_T **lasts); 
                                                                 ^ 
c:/ace/6.2.1-qt/ACE_wrappers/ace/Basic_Types.h:317:23: error: expected ')' before 'wchar_t' 
 #  define ACE_WCHAR_T wchar_t 
                       ^ 
c:/ace/6.2.1-qt/ACE_wrappers/ace/OS_NS_string.h:449:65: note: in expansion of macro 'ACE_WCHAR_T' 
   wchar_t *strtok_r (ACE_WCHAR_T *s, const ACE_WCHAR_T *tokens, ACE_WCHAR_T **lasts); 
                                                                 ^ 
c:/ace/6.2.1-qt/ACE_wrappers/ace/Basic_Types.h:317:23: error: expected initializer before 'wchar_t' 
 #  define ACE_WCHAR_T wchar_t 
                       ^ 
c:/ace/6.2.1-qt/ACE_wrappers/ace/OS_NS_string.h:449:65: note: in expansion of macro 'ACE_WCHAR_T' 
   wchar_t *strtok_r (ACE_WCHAR_T *s, const ACE_WCHAR_T *tokens, ACE_WCHAR_T **lasts); 
                                                                 ^ 
/c/ace/6.2.1-qt/ACE_wrappers//include/makeinclude/rules.local.GNU:188: recipe for target `.shobj/Name_Proxy.o' failed 
make[1]: *** [.shobj/Name_Proxy.o] Error 1 
make[1]: Leaving directory `/c/ace/6.2.1-qt/ACE_wrappers/ace' 
GNUmakefile:43: recipe for target `ACE' failed 
make: *** [ACE] Error 2 

    DOES THE PROBLEM AFFECT: 
        COMPILATION? YES 
        LINKING? 
            On Unix systems, did you run make realclean first? 
        EXECUTION? N/A 
        OTHER (please specify)? N/A 

    SYNOPSIS: 
ACE build with Qt5.1.1 mingw fails. 

    DESCRIPTION: 
Attempting to build ACE for use with Qt 5.1.1, using the supplied mingw48_32 compiler. Installed numerous different mingwbuilds toolchain releases and noticed that builds using posix threading always fail in above manner. ACE will compile fine using mingw built with win32 model. 

    REPEAT BY: 
Install msys, point it at the Qt mingw toolchain via /etc/fstab, configure ACE per the directions online  (http://www.dre.vanderbilt.edu/~schmidt/DOC_ROOT/ACE/ACE-INSTALL.html#mingw). 
                 
                 
    SAMPLE FIX/WORKAROUND: 
Proposed patch to fix this issue (undef buggy glib pthread macros for "recursive API emulation"). Note that this was tested only on a win32 machine running windows 7 SP1:

--- OS_NS_string.h.orig	2013-09-24 10:34:12 -0400
+++ OS_NS_string.h	2013-09-24 10:02:34 -0400
@@ -34,6 +34,11 @@
 #endif
 #define ACE_EXPORT_MACRO ACE_Export
 
+#if defined WIN_PTHREADS_H
+	#undef strtok_r
+	#undef rand_r
+#endif
+
 ACE_BEGIN_VERSIONED_NAMESPACE_DECL
 
 namespace ACE_OS {
--- OS_NS_stdlib.h.orig	2013-09-24 10:34:26 -0400
+++ OS_NS_stdlib.h	2013-09-24 10:05:31 -0400
@@ -30,6 +30,10 @@
 
 #include "ace/Basic_Types.h"  /* ACE_UINT64 and intptr_t in inl file */
 
+#if defined WIN_PTHREADS_H
+	#undef rand_r
+#endif
+
 #if defined (ACE_EXPORT_MACRO)
 #  undef ACE_EXPORT_MACRO
 #endif
--- OS_NS_time.h.orig	2013-09-24 10:34:35 -0400
+++ OS_NS_time.h	2013-09-24 10:07:20 -0400
@@ -31,6 +31,14 @@
 
 #include /**/ "ace/ACE_export.h"
 
+#if defined WIN_PTHREADS_H
+	#undef gmtime_r
+	#undef localtime_r
+	#undef ctime_r
+	#undef asctime_r
+#endif
+
+
 #if defined (ACE_EXPORT_MACRO)
 #  undef ACE_EXPORT_MACRO
 #endif

**Comment by jwillemsen** [comment]
_Originally posted by Martin Kolleck on 2015-12-03 14:50:55 -0600_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=4133#c1))

---

Created attachment [1520](https://raw.githubusercontent.com/DOCGroup/bugzilla/main/attachments/BZ-4133/ace-mingw32-pthread.patch)
Patch against ACE-6.3.3.

This is still an issue with the latest Qt 5.5.1 and ACE 6.3.3.

| Field | Value |
| --- | --- |
| **Attachment ID** | [1520](http://bugzilla.dre.vanderbilt.edu/attachment.cgi?id=1520) |
| **Filename** | `ace-mingw32-pthread.patch` |
| **Description** | Patch against ACE-6.3.3. |
| **Uploaded by** | Martin Kolleck |
| **Date** | 2015-12-03 14:50:55 -0600 |
| **Size** | 1388 bytes |
| **Patch** | yes |
| **Obsolete** | no |
| **Download** | [Download from repository](https://raw.githubusercontent.com/DOCGroup/bugzilla/main/attachments/BZ-4133/ace-mingw32-pthread.patch) |

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2015-12-04 01:33:01 -0600_ ([Bugzilla comment 2](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=4133#c2))

---

Please make a pull request add https://github.com/DOCGroup/ATCD/, extend your patch to check first with (if defined ...) and only undef when it is defined.
