### ISSUE TITLE
[BZ-1907] Linux's Recursive_Thread_Mutex + get_nesting_level = broken

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#1907]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [1907](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1907) |
| **Reporter** | Markus Stenberg |
| **Assigned to** | DOC Center Support List (internal) |
| **Product** | ACE |
| **Component** | ACE Core |
| **Version** | 5.4.1 |
| **Platform / OS** | x86 / Linux |
| **Priority** | P4 |
| **Severity** | normal |
| **Status** | RESOLVED |
| **Resolution** | WONTFIX |
| **Created** | 2004-08-13 02:55:48 -0500 |

---

_Originally posted by Markus Stenberg on 2004-08-13 02:55:48 -0500_

---

Apparently (at least as of 5.4?) ACE seems to use built-in mutexes as they are
recursive. However, it breaks the nesting level calculation which is pain if
it's actually used for something.

I understand the reasoning behind the code (yes, returning -1 versus keeping
extra count is MUCH more efficient), but effectively it raises some significant
questions about PORTABILITY; do ACE functions in general also have this 'return
error if not supported' trend? 

Finding this out at compilation-time (for example, in the header, just exclude
feature altogether using #ifdef if not supported and provide define-per-feature)
would be MUCH more preferable as I'd get controlled compilation errors, compared
to finding myself in gdb after some assertions.

This sucked especially as the change was NOT documented in any fashion and broke
code that worked with 5.3 and before.

**Comment by jwillemsen** [comment]
_Originally posted by Douglas C. Schmidt on 2004-08-13 12:12:09 -0500_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1907#c1))

---

Please see the discussions in Appendix A.5 of C++NPv1 
<www.cs.wustl.edu/~schmidt/ACE/book1/> for an overview of ACE's portability 
strategy.  As for the release notes, I recommend you check with Steve Huston 
<shuston@riverace.com> since he's the one who added this capability.

**Comment by jwillemsen** [comment]
_Originally posted by Douglas C. Schmidt on 2004-08-13 15:53:30 -0500_ ([Bugzilla comment 2](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1907#c2))

---

Markus, this change took place between ACE 5.4.1 and ACE 5.4.2.  Please see

$ACE_ROOT/NEWS

for an overview of the change, which I've enclosed below:

. Support for Pthreads native recursive mutexes was added. This
  capability is specified to ACE_OS::mutex_init() as an optional
  argument, lock_type. To fix confusion from an earlier attempt to add
  this functionality, the meaning of the old 'type' argument to
  ACE_OS::thread_mutex_init() is changed. It previously combined the
  scope and type. Now it is just the type (e.g. recursive), as the
  scope is inherent in the method used. For clarification on
  ACE_HAS_RECURSIVE_MUTEXES, it means that the platform is capable of
  them, not that they always are, as one would expect. However, before
  Pthreads had recursion added, it was never optional. Now it is.

**Comment by jwillemsen** [comment]
_Originally posted by Markus Stenberg on 2004-08-16 04:03:21 -0500_ ([Bugzilla comment 3](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1907#c3))

---

I'm aware of the release notes. However, they mentioned only something being
fixed, not API being broken. I'm too lazy to look up book in our library just
for the explanation so I'll have to just deal with this :)
