### ISSUE TITLE
[BZ-1906] Sometimes #include "tao/Valuetype/AbstractBase_Invocation_Adapter.h" include is missing

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#1906]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [1906](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906) |
| **Reporter** | Markus Stenberg |
| **Assigned to** | Jeff Parsons |
| **Product** | TAO |
| **Component** | IDL Compiler |
| **Version** | 1.4.1 |
| **Platform / OS** | x86 / Linux |
| **Priority** | P3 |
| **Severity** | normal |
| **Status** | RESOLVED |
| **Resolution** | FIXED |
| **Created** | 2004-08-13 01:58:32 -0500 |

---

_Originally posted by Markus Stenberg on 2004-08-13 01:58:32 -0500_

---

When playing with heavily OBV-using codebase, both 1.4 and 1.4.1 exhibit strange
behavior: In most files, #include
"tao/Valuetype/AbstractBase_Invocation_Adapter.h" is present.

In some it isn't, but the adapter is still referenced -> compilation error. This
is extremely frustrating. Same stuff worked fine with 1.3.[345] and old CVS
versions as well.

I can maybe provide some idl files if need be, but they're pretty standard stuff.

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2004-08-13 02:00:31 -0500_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c1))

---

Having a testcase will help, could you add some test case?

**Comment by jwillemsen** [comment]
_Originally posted by Markus Stenberg on 2004-08-13 02:10:04 -0500_ ([Bugzilla comment 2](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c2))

---

Okay. I spent some time playing with files (for some reason our company frowns
on sending any internal .idl files out, don't ask me why :->) and I actually
narrowed out the reason. Basically, it does not count included and implemented
abstract interfaces correctly, as far as I see it.. (f2.idl's output f2C.cpp
does not compile)

Sample:

f1.idl:
abstract interface AI
{
};

interface I : AI
{
};

f2.idl:
#include "f1.idl"

interface I2 : AI
{
};

**Comment by jwillemsen** [comment]
_Originally posted by Markus Stenberg on 2004-08-13 02:11:23 -0500_ ([Bugzilla comment 3](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c3))

---

.. and I'm fairly sure it won't happen unless OBV support is turned on for
obvious reasons (I was too lazy to test it, to be frank).

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2004-08-13 02:22:40 -0500_ ([Bugzilla comment 4](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c4))

---

Could you retest with x.4.2, several things have been fixed and the doc_group 
just hasn't time to retest everything.

**Comment by jwillemsen** [comment]
_Originally posted by Markus Stenberg on 2004-08-13 02:37:16 -0500_ ([Bugzilla comment 5](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c5))

---

I can and probably also will it's released; downloading huge tarballs isn't my
idea of fun, and apparently you guys lack anonymous CVS access. Playing with
tarballs without incremential recompilation takes simply too much time (sure, it
can be hacked but it's not worth it; I also figured workaround for the bug that
allows me to use 1.4.1 for what I need anyway).

**Comment by jwillemsen** [comment]
_Originally posted by Douglas C. Schmidt on 2004-08-13 10:44:43 -0500_ ([Bugzilla comment 6](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c6))

---

Hi Markus,

Please see

http://cvs.doc.wustl.edu/

for instructions on how to use anonymous CVS to obtain ACE+TAO piece-meal or 
wholesale, at your discretion.  Jeff, can you please take a look at Markus's 
bug report to see if this is something you've already fixed in x.4.2?

**Comment by jwillemsen** [comment]
_Originally posted by Jeff Parsons on 2004-08-13 12:32:24 -0500_ ([Bugzilla comment 7](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c7))

---

This has been fixed for 1.4.2:

Fri Apr 30 16:29:39 2004  Jeff Parsons <j.parsons@vanderbilt.edu>

        * TAO_IDL/be/be_interface.cpp:

          Changed the setting of the internal IDL compler flag for
          encountering an abstract interface to happen not only
          when an interface is abstract but also when it has an
          abstract parent. This change is because the abstract
          parent may be declared in an included IDL file, and
          inclusion of AbstractBase.cpp and Abstract_Invocation_Base.cpp
          generated by that file may have come in the stub source file,
          in which case the inclusion will have to be repeated in the
          stub source file generated from the main IDL file.


Also, a previous comment says "..unless OBV support is turned on...". For the 
record, OBV support has been on by default for quite some time.

**Comment by jwillemsen** [comment]
_Originally posted by Markus Stenberg on 2004-08-16 04:13:34 -0500_ ([Bugzilla comment 8](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c8))

---

My code _compiles_ under .4.2. However, it doesn't really work.

Abstract interfaces have some issues it seems, I'll get back to it if I find the
time to write reproducible bug report on the topic - it seems that the indirect
dispatching in abstractbase_invocation_adapter attempts to use NULL stub for
some reason in my inheritance hierarchy, while it works if I just remove the
abstract interfaces' abstract declaration which was originally added just for
completeness (but doesn't seem to work too well under .4.* - it used to work on
.3.*).

Disclaimer: I am aware of abstract interface<>interface semantical differences,
but I'm using just concrete interfaces in all the code anyway and just
superclass is abstract if, and it still breaks things for some funny reason..

**Comment by jwillemsen** [comment]
_Originally posted by Douglas C. Schmidt on 2004-08-16 07:46:49 -0500_ ([Bugzilla comment 9](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c9))

---

Hi Markus,  

It would be great to get a small example that illustrated the problem since 
right now it's hard to know what's going on.  Jeff, do you have any examples of 
this stuff in any of the TAO regression tests?

**Comment by jwillemsen** [comment]
_Originally posted by Jeff Parsons on 2004-08-16 15:03:38 -0500_ ([Bugzilla comment 10](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c10))

---

Please see the test in TAO/tests/Abstract_Interface, in which an abstract 
interface is defined, along with a concrete interface that inherits from it 
and a valuetype that supports it. One of these two is then passed back to the 
client as an out parameter of the type of the abstract interface. By default 
the test is run 3 times - once to check a remote call (pass by reference), 
once to check state (pass by value) and once to check exception handling. If
one of these does not cover your use case, please send along a simple example 
that illustrates the problem, and I'll take a look. I just tried the test and 
it worked fine.

**Comment by jwillemsen** [comment]
_Originally posted by Markus Stenberg on 2004-08-17 04:19:30 -0500_ ([Bugzilla comment 11](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c11))

---

Okay.. I wrote extremely simple sample file which exhibits the problem for me in
the *.4.2 - there's 3 workarounds to make it work correctly:

------------------------------------------
// remove abstract -> works
abstract interface AI
{
    oneway void f();
};

interface I2 : AI
{
    // remove the comment below -> works
    //oneway void reportGenericText(in string s);
};

interface I : I2
              // or replace I2 with AI -> works
{

};
------------------------------------------

If none of the commented workarounds are done, the generated code which
implements the POA_I and f() will simply crash with simple o->_this()->f() call.

**Comment by jwillemsen** [comment]
_Originally posted by Jeff Parsons on 2004-08-17 16:02:51 -0500_ ([Bugzilla comment 12](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1906#c12))

---

Tue Aug 17 15:48:28 2004  Jeff Parsons <j.parsons@vanderbilt.edu>

        * TAO_IDL/be/be_interface.cpp:
        
          Changed the logic of the check for 'mixed parentage'
          (abstract & concrete) in an interface, to return true not
          only if an interface has an immediate abstract parent (as
          before) but also if there is an abstract interface 
          anywhere in its ancestry. This is necessary for skeletons-side
          code generation, since abstract interfaces have no operations
          generated on the skeleton side for children to inherit, the
          operations must be regenerated in each child.
          
        * TAO_IDL/be/be_visitor_interface/direct_proxy_impl_sh.cpp:
        * TAO_IDL/be/be_visitor_interface/direct_proxy_impl_ss.cpp:
        * TAO_IDL/be/be_visitor_interface/interceptors_ss.cpp:
        * TAO_IDL/be/be_visitor_interface/interface.cpp:
        * TAO_IDL/be/be_visitor_interface/interface_ch.cpp:
        * TAO_IDL/be/be_visitor_interface/interface_cs.cpp:
        * TAO_IDL/be/be_visitor_interface/interface_sh.cpp:
        * TAO_IDL/be/be_visitor_interface/interface_ss.cpp:
        * TAO_IDL/be/be_visitor_interface/thru_poa_proxy_impl_sh.cpp:
        * TAO_IDL/be/be_visitor_interface/thru_poa_proxy_impl_ss.cpp:
        
          For the gen_abstract_ops_helper() static method in each of the
          above visitors, changed the logic to do nothing unless the
          base interface passed to the method is abstract. The check
          has been moved here from its former location in the method
          call so operations inherited from distance abstract ancestors
          can be found and regenerated. Thanks to Markus Stenberg
          <markus.stenberg@conformiq.com> for sending in an example that
          uncovered the bug.
