### ISSUE TITLE
[BZ-972] possible missing define

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#972]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [972](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=972) |
| **Reporter** | Lukas Gruetzmacher |
| **Assigned to** | DOC Center Support List (internal) |
| **Product** | ACE |
| **Component** | ACE Core |
| **Version** | 5.1.16 |
| **Platform / OS** | x86 / Windows NT |
| **Priority** | P3 |
| **Severity** | major |
| **Status** | RESOLVED |
| **Resolution** | FIXED |
| **Created** | 2001-07-12 09:38:41 -0500 |

---

_Originally posted by Lukas Gruetzmacher on 2001-07-12 09:38:41 -0500_

---

I've tried to compile my project (comming from Visibroker 4.1).
I've included only files beginning with "afx" and IDL generated files.
The compiler run results in:
Compiling...
StdAfx.cpp
e:\Ace_wrappers\ace/OS.i(2384) : error C2039: 'TryEnterCriticalSection' : is 
not a member of '`global namespace''
e:\Ace_wrappers\ace/OS.i(2384) : error C2065: 'TryEnterCriticalSection' : 
undeclared identifier

Searching the reason I found _WIN32_WINNT is not defined to 0x0400 although I'm 
running such a system. So I tried to define this as follows:
#define _WIN32_WINNT 0x0400
before including generated CORBA files.
This results in winbase.h the definition of ::TryEnterCriticalSection and the 
compiler runs successfull.

BUT NOW: On Runtime the call ORB_init fails in
ACE_TSS_Cleanup::instance (void) on ACE_TSS_CLEANUP_GUARD.
The array ACE_OS_Object_Manager::preallocated_object is 3 fields long (info 
from debugger) and all 3 are NULL. So ACE_TSS_CLEANUP_GUARD will crash inside 
on calling ::EnterCriticalSection with NULL.

It's a compiler/configuration problem (_WIN32_WINNT) or software problem 
(initialization of ACE_OS_Object_Manager::preallocated_object)

Later I've tried to compile with 5.1.18 but TryEnterCriticalSection can still 
not be found. In this version I've still not tested for possible same crash 
scenario.

**Comment by jwillemsen** [comment]
_Originally posted by Douglas C. Schmidt on 2001-07-12 09:58:38 -0500_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=972#c1))

---

Make sure to include the "ace/OS.h" file before *any* of your header files are 
included.  This will fix the problem you're having.
