### ISSUE TITLE
[BZ-1822] Problems in Compiling ACE.  Configuration.cpp:1361 virtual functions are abstract.

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#1822]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [1822](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1822) |
| **Reporter** | Ciaran Moran |
| **Assigned to** | DOC Center Support List (internal) |
| **Product** | ACE |
| **Component** | ACE Core |
| **Version** | 5.4 |
| **Platform / OS** | SPARC / Solaris |
| **Priority** | P1 |
| **Severity** | blocker |
| **Status** | RESOLVED |
| **Resolution** | FIXED |
| **Created** | 2004-05-18 09:49:11 -0500 |

---

_Originally posted by Ciaran Moran on 2004-05-18 09:49:11 -0500_

---

config.h contains: #include "ace/config-sunos5.8.h"
platform_macros.GNU contains: 
include $(ACE_ROOT)/include/makeinclude/platform_sunos5_g++.GNU

when I compile from $ACE_ROOT/ace I get the following output.

Configuration.cpp: In member function `int ACE_Configuration_Heap::open(int)':
Configuration.cpp:1361: cannot allocate an object of type `HEAP_ALLOCATOR'
Configuration.cpp:1361:   because the following virtual functions are abstract:
/export/home/night/acetao/ACE_wrappers/ace/Malloc_Base.h:87:    virtual int
   ACE_Allocator::bind(const char*, void*, int = 0)
Configuration.cpp: In member function `int ACE_Configuration_Heap::open(const
   ACE_TCHAR*, void*, int)':
Configuration.cpp:1394: cannot allocate an object of type
   `PERSISTENT_ALLOCATOR'
Configuration.cpp:1394:   because the following virtual functions are abstract:
/export/home/night/acetao/ACE_wrappers/ace/Malloc_Base.h:87:    virtual int
   ACE_Allocator::bind(const char*, void*, int = 0)
Configuration.cpp: In member function `int
   ACE_Configuration_Heap::create_index()':
Configuration.cpp:1431: no matching function for call to
   `ACE_Allocator::__xnet_bind(const char[21], void*&)'
make[1]: *** [.shobj/Configuration.o] Error 1
make[1]: Leaving directory `/export/home/night/acetao/ACE_wrappers/ace'
make: *** [all] Error 2

**Comment by jwillemsen** [comment]
_Originally posted by Ossama Othman on 2004-06-09 00:20:34 -0500_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1822#c1))

---

We don't see this problem in our Solaris build with g++ 2.95.x.  Would happen to
know if this problem also exists with g++ 3.4?

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2004-06-11 05:31:25 -0500_ ([Bugzilla comment 2](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1822#c2))

---

Got the following by e-mail. Please use bugzilla to respond to bugs in the 
future.

Hello folks,

    Sorry for not getting back to you sooner. The problem arose for us when 
using gcc 3.0.3. We upgraded to gcc 3.2.2 and that fixed the problem. 3.2.2 is 
the compiler we currently use.

cheers
Ciaran.
