### ISSUE TITLE
[BZ-587] examples/IOStream/server/iostream_server.cpp doesn't build with Sun CC 5.0

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#587]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [587](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=587) |
| **Reporter** | levine |
| **Assigned to** | DOC Center Support List (internal) |
| **Product** | ACE |
| **Component** | ACE Example |
| **Version** | 5.1.3 |
| **Platform / OS** | SPARC / Solaris |
| **Priority** | P5 |
| **Severity** | normal |
| **Status** | RESOLVED |
| **Resolution** | FIXED |
| **Created** | 2000-06-08 11:24:50 -0500 |

---

_Originally posted by levine on 2000-06-08 11:24:50 -0500_

---

From Dave McNeely <Dave_McNeely@md.northgrum.com>:

                CC -mt -g -library=iostream,no%Cstd -instances=explicit \
                        -noex  -DACE_NO_INLINE  \
                        -I/home/davemc/tao/ACE_wrappers  -c \
                        -o .obj/iostream_server.o iostream_server.cpp

        which produces the following errors:
"iostream_server.h", line 37: Error: Template parameter
_ACE_SYNCH_CONDITION_T requires a type argument.
"/home/davemc/tao/ACE_wrappers/ace/Svc_Handler.h", line 34: Error: The base
"ACE_Task<>" must be a previously defined class or struct.
"iostream_server.h", line 37:     Where: While specializing
"ACE_Svc_Handler<ACE_IOStream<ACE_SOCK_Stream>>".
"iostream_server.h", line 37:     Where: Specialized in non-template code.
"iostream_server.cpp", line 20: Error: reactor is not a member of Handler.
"iostream_server.cpp", line 142: Error: Template parameter
_ACE_SYNCH_CONDITION_T requires a type argument.
