### ISSUE TITLE
[BZ-88] Dup symbols when linking shared library on AIX w/ egcs

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#88]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [88](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=88) |
| **Reporter** | @shuston |
| **Assigned to** | @shuston |
| **Product** | ACE |
| **Component** | ACE Core |
| **Version** | 4.6.45 |
| **Platform / OS** | PowerPC / AIX |
| **Priority** | P4 |
| **Severity** | trivial |
| **Status** | RESOLVED |
| **Resolution** | WONTFIX |
| **Created** | 1999-07-22 15:34:18 -0500 |

---

_Originally posted by @shuston on 1999-07-22 15:34:18 -0500_

---

Each shared library that's linked has this warning displayed:

ld: 0711-224 WARNING: Duplicate symbol: ._GLOBAL__DI
ld: 0711-224 WARNING: Duplicate symbol: ._GLOBAL__DD
ld: 0711-224 WARNING: Duplicate symbol: _GLOBAL__DI
ld: 0711-224 WARNING: Duplicate symbol: _GLOBAL__DD
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.

The libraries appear to work fine, but unexplained dups are discomforting.

**Comment by jwillemsen** [comment]
_Originally posted by @shuston on 1999-07-22 15:35:59 -0500_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=88#c1))

---

Accepted. I've posted a query on this to gnu.g++.help, but no reply as yet.

**Comment by jwillemsen** [comment]
_Originally posted by @shuston on 2003-01-10 09:20:33 -0600_ ([Bugzilla comment 2](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=88#c2))

---

This now works fine on AIX with g++ 3.2. Since egcs is old and never really 
worked well on AIX anyway, this won't be fixed.
