### ISSUE TITLE
[BZ-2922] Failed to build ACE because _byteswap_ushort, _byteswap_ulong, _byteswap_uint64 is nonexistent  in WINCE

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#2922]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [2922](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922) |
| **Reporter** | Xu Liang |
| **Assigned to** | DOC Center Support List (internal) |
| **Product** | ACE |
| **Component** | ACE Core |
| **Version** | 5.5.8 |
| **Platform / OS** | x86 / other |
| **Priority** | P3 |
| **Severity** | normal |
| **Status** | RESOLVED |
| **Resolution** | FIXED |
| **Created** | 2007-05-05 03:13:53 -0500 |

---

_Originally posted by Xu Liang on 2007-05-05 03:13:53 -0500_

---

When I build ACE for Windows CE. I got a build error. 
1>..\ace/CDR_Base.inl(8) : warning C4164: '_byteswap_ushort' : intrinsic function not declared
1>..\ace/CDR_Base.inl(8) : warning C4164: '_byteswap_ulong' : intrinsic function not declared
1>..\ace/CDR_Base.inl(8) : warning C4164: '_byteswap_uint64' : intrinsic function not declared
1>..\ace/CDR_Base.inl(72) : error C3861: '_byteswap_ushort': identifier not found

The _byteswap_ushort, _byteswap_ulong, _byteswap_ushort is nonexistent in Windows CE.

**Comment by jwillemsen** [comment]
_Originally posted by Xu Liang on 2007-05-05 03:14:54 -0500_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922#c1))

---

Created attachment [778](https://raw.githubusercontent.com/DOCGroup/bugzilla/main/attachments/BZ-2922/CDR_Base.inl)
My Patch.

| Field | Value |
| --- | --- |
| **Attachment ID** | [778](http://bugzilla.dre.vanderbilt.edu/attachment.cgi?id=778) |
| **Filename** | `CDR_Base.inl` |
| **Description** | My Patch. |
| **Uploaded by** | Xu Liang |
| **Date** | 2007-05-05 03:14:54 -0500 |
| **Size** | 8884 bytes |
| **Patch** | no |
| **Obsolete** | no |
| **Download** | [Download from repository](https://raw.githubusercontent.com/DOCGroup/bugzilla/main/attachments/BZ-2922/CDR_Base.inl) |

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-05-05 14:17:55 -0500_ ([Bugzilla comment 2](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922#c2))

---

thanks for reporting this, looks that we should introduce some new defines like I have done for the bswap methods. then these defines can be set in the config files

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-05-07 08:09:33 -0500_ ([Bugzilla comment 3](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922#c3))

---

please provide your full config.h version and the IDE you are using and the target architecture, we don't see this errors in the tao wince 5 build that is on the scoreboard, so disabling this fully for wince is not a good thing todo

**Comment by jwillemsen** [comment]
_Originally posted by Xu Liang on 2007-05-07 10:28:08 -0500_ ([Bugzilla comment 4](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922#c4))

---

My IDE is VC8 and target architecture is Pocket PC 2003.

My config.h :

// Define 32BIT time_t, ensures Time_Value is
// correctly initialised from a time_t of 0
#define _USE_32BIT_TIME_T

// WinCE definition of time_t in stdlib.h does not conform to POSIX
// This definition must appear before stdlib.h is included
// Define _TIME_T_DEFINED to suppress definition of time_t in stdlib.h

typedef long  time_t;		/* POSIX conformant */
#define _TIME_T_DEFINED

#include "config-win32.h"

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-05-07 12:51:16 -0500_ ([Bugzilla comment 5](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922#c5))

---

that seems to match the build with the results on the link below. have you installed all patches? Disabling this fully for wince seems a real bad thing

http://acebuilds.riverace.com/lily/dev/vc8_winmobile5_debug/index.html

**Comment by jwillemsen** [comment]
_Originally posted by @shuston on 2007-05-07 13:01:55 -0500_ ([Bugzilla comment 6](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922#c6))

---

The build fails on our VC8 PocketPC 2003 build (the one referenced by Johnny). I'll work on this before ACE 5.6 is released. If you need it integrated quicker than that, please contact me for support.

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-05-07 13:06:17 -0500_ ([Bugzilla comment 7](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922#c7))

---

steve, your build doesn't show these specific errors but others, are you sure that the byteswap usage does give errors?

**Comment by jwillemsen** [comment]
_Originally posted by @shuston on 2007-05-07 13:14:40 -0500_ ([Bugzilla comment 8](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922#c8))

---

Yes:
[Details] 1>..\ace/CDR_Base.inl(8) : warning C4164: '_byteswap_ushort' : intrinsic function not declared
[Details] 1>..\ace/CDR_Base.inl(8) : warning C4164: '_byteswap_ulong' : intrinsic function not declared
[Details] 1>..\ace/CDR_Base.inl(8) : warning C4164: '_byteswap_uint64' : intrinsic function not declared
[Details] 1>..\ace/CDR_Base.inl(72) : error C3861: '_byteswap_ushort': identifier not found
[Details] 1>..\ace/CDR_Base.inl(103) : error C3861: '_byteswap_ulong': identifier not found
[Details] 1>..\ace/CDR_Base.inl(135) : error C3861: '_byteswap_uint64': identifier not found

**Comment by jwillemsen** [comment]
_Originally posted by @jwillemsen on 2007-05-07 13:17:27 -0500_ ([Bugzilla comment 9](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922#c9))

---

I think you refer to the wince4 build, not to wince5 as I thought. So only this has to be done for wince4,

**Comment by jwillemsen** [comment]
_Originally posted by @shuston on 2007-05-07 17:33:36 -0500_ ([Bugzilla comment 10](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2922#c10))

---

Fixed:
Mon May  7 22:18:55 UTC 2007  Steve Huston  <shuston@riverace.com>

        * ace/config-win32-msvc-7.h:
        * ace/config-win32-msvc-8.h:
        * ace/config-win32-msvc-9.h:
          Added ACE_HAS_INTRINSIC_BYTESWAP for all except WinCE 4.
          For config-win32-msvc-9.h, comment the #if block around
          ACE_HAS_INTRINSIC_INTERLOCKED; if a build with this compiler and
          WinCE shows it needs to be uncommented (as for previous MSVC
          versions) it can be changed then.

        * ace/CDR_Base.inl: Replace complicated #if around the byteswap
          usage with #if defined (ACE_HAS_INTRINSIC_BYTESWAP).

          This fixes Bugzilla #2922. Thanks to Xu Liang for reporting it.

        * THANKS: Added Xu Liang.
