### ISSUE TITLE
[BZ-1858] ACE beta fails to build with g++ 3.4.0.

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#1858]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [1858](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1858) |
| **Reporter** | njs |
| **Assigned to** | DOC Center Support List (internal) |
| **Product** | ACE |
| **Component** | ACE gperf |
| **Version** | 5.4.1 |
| **Platform / OS** | x86 / Linux |
| **Priority** | P3 |
| **Severity** | normal |
| **Status** | RESOLVED |
| **Resolution** | FIXED |
| **Created** | 2004-06-20 02:45:54 -0500 |

---

_Originally posted by njs on 2004-06-20 02:45:54 -0500_

---

I downloaded the latest ACE beta from http://deuce.doc.wustl.edu/ACE.tar.bz2 on
2004-06-19, and attempted to compile it with the FSF's 3.4.0 release of g++. 
Unlike 5.4, it mostly worked; unfortunately, there was still a minor compile
error, pasted below.  While it is possible to work around by calling 'make -k',
this doesn't play well with automated building...

make[6]: Entering directory `/home/njs/ACE_wrappers/apps/gperf/tests'

Makefile: /home/njs/ACE_wrappers/apps/gperf/tests/Makefile

/home/njs/3.4.0/install/bin/g++ -W -Wall -Wpointer-arith -g -O2 -pipe 
-D_REENTRANT -DACE_HAS_AIO_CALLS -D_GNU_SOURCE   -I/home/njs/ACE_wrappers
-DACE_NDEBUG -DACE_USE_RCSID=0 -DACE_HAS_EXCEPTIONS -D__ACE_INLINE__  -Wl,-E
-L/home/njs/ACE_wrappers/ace -L./ -o cout .obj/test.o .obj/cinset.o  -lACE -ldl
-lpthread -lrt 
.obj/test.o: In function `main':
/home/njs/ACE_wrappers/apps/gperf/tests/test.cpp:28: undefined reference to
`in_word_set(char const*, unsigned int)'
collect2: ld returned 1 exit status

**Comment by jwillemsen** [comment]
_Originally posted by Nanbor Wang on 2004-06-20 06:47:34 -0500_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=1858#c1))

---

Support for g++ 3.4 was added after 5.4.1. The upcoming beta (5.4.2) with the 
support should be available in the next week or so.
