### ISSUE TITLE
[BZ-2362] Failed to compile $ACE_ROOT/TAO/orbsvcs/examples/ImR/Combined_Service

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/bugzilla#2362]
| Field | Value |
| --- | --- |
| **Bugzilla ID** | [2362](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2362) |
| **Reporter** | ianzag |
| **Assigned to** | DOC Center Support List (internal) |
| **Product** | TAO |
| **Component** | Example |
| **Version** | 1.4.8 |
| **Platform / OS** | x86 / NetBSD |
| **Priority** | P3 |
| **Severity** | normal |
| **Status** | RESOLVED |
| **Resolution** | FIXED |
| **Created** | 2006-01-16 01:10:38 -0600 |

---

_Originally posted by ianzag on 2006-01-16 01:10:38 -0600_

---

Please note: ACE/TAO is build with STLport v4.6, not a GNU STL.

---cut---
GNUmakefile:
/usr/local/ACE/ACE_wrappers-5.4.8/TAO/orbsvcs/examples/ImR/Combined_Service/GNUmakefile.ImR_Combined_Service_Test
MAKEFLAGS=w

g++ -W -Wall -Wpointer-arith -nostdinc++ -I/usr/pkg/include/stlport
-I/usr/include/g++ -I/usr/pkg/include -D_REENTRANT -DACE_HAS_THREADS -O2 -g
-pipe      -I/usr/local/ACE/ACE_wrappers -I/usr/local/ACE/ACE_wrappers/TAO 
-DACE_HAS_EXCEPTIONS -D__ACE_INLINE__    -I/usr/local/ACE/ACE_wrappers
-I/usr/local/ACE/ACE_wrappers/TAO  -c -o .obj/test.o test.cpp
test.cpp: In function `int main(int, char**)':
test.cpp:29: error: no matching function for call to `_STL::runtime_error::
   runtime_error(const char*)'
/usr/pkg/include/stlport/stdexcept:91: error: candidates are: 
   _STL::runtime_error::runtime_error(const _STL::runtime_error&)
/usr/pkg/include/stlport/stdexcept:93: error:                 
   _STL::runtime_error::runtime_error(const _STL::string&)
test.cpp:33: error: no matching function for call to `_STL::runtime_error::
   runtime_error(const char*)'
/usr/pkg/include/stlport/stdexcept:91: error: candidates are: 
   _STL::runtime_error::runtime_error(const _STL::runtime_error&)
/usr/pkg/include/stlport/stdexcept:93: error:                 
   _STL::runtime_error::runtime_error(const _STL::string&)
gmake[1]: *** [.obj/test.o] Error 1
gmake[1]: Leaving directory
`/usr/local/ACE/ACE_wrappers-5.4.8/TAO/orbsvcs/examples/ImR/Combined_Service'
gmake: *** [ImR_Combined_Service_Test] Error 2
---cut---

Fix is simple: do not forget to add <string> if you refer to std::string :)

---cut---
# diff -u test.cpp.orig test.cpp 
--- test.cpp.orig       2005-05-16 21:23:52.000000000 +0700
+++ test.cpp    2006-01-16 13:04:43.000000000 +0600
@@ -4,6 +4,7 @@
 #include "testC.h"
 
 #include <stdexcept>
+#include <string>
 #include "ace/SString.h"
 #include "ace/Log_Msg.h"
 #include "ace/OS_NS_stdio.h"
---cut---

// wbr

**Comment by jwillemsen** [comment]
_Originally posted by Douglas C. Schmidt on 2006-01-16 05:52:30 -0600_ ([Bugzilla comment 1](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=2362#c1))

---

Fixed, thanks!

Doug
